Exceptions.
print()
first_value = 10

try:
    print(second_value)
except:
    print("An error has occured because second_value does not exist.")

print()
