NameError.
try:
    print(second_value)
except NameError as msg:
    print("An error has occured because second_value does not exist: \n",msg)

print()
